name: Build static analysis tool with custom plugins
on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker-build:
    runs-on: ubuntu-latest
    env:
      BUILD: ${{ github.event.number }}
    steps:
      - name: Git clone
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Log into Github registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Docker build
        run: |
          docker build -t ghcr.io/golang-cz/static-analysis-$BUILD .
          docker push ghcr.io/vcilabs/static-analysis-$BUILD
